name: CI

on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.org'
    - '.dir-locals.el'
    - '.elpaignore'
    - '.gitignore'
    - 'doc/**'
    branches: [main, master]
  push:
    paths-ignore:
    - '**.md'
    - '**.org'
    - '.dir-locals.el'
    - '.elpaignore'
    - '.gitignore'
    - 'doc/**'
    branches: [main, master]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          # - 28.2
          # - 29.4
          - 30.1
        experimental: [false]
        include:
        - os: ubuntu-latest
          emacs-version: snapshot
          experimental: true
        - os: macos-latest
          emacs-version: snapshot
          experimental: true
        - os: windows-latest
          emacs-version: snapshot
          experimental: true

    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Pull poly-markdown
      uses: actions/checkout@v4
      with:
        repository: polymode/poly-markdown

    - name: Pull poly-org
      uses: actions/checkout@v4
      with:
        repository: polymode/poly-org

    - name: Pull poly-noweb
      uses: actions/checkout@v4
      with:
        repository: polymode/poly-noweb

    - name: Pull polymode
      uses: actions/checkout@v4

    - name: Check Emacs version
      run: emacs --version

    - name: ELPA
      run: make elpa

    - name: Build
      run: make build

    - name: Test
      run: make test-local

    - name: Test poly-markdown
      working-directory: ../poly-markdown
      run: |
        eask link add polymode ../polymode
        eask install-deps --dev
        eask test ert ./tests/*.el
